#!/bin/sh
# Setup a machine for Sublime Text
set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$ZSH/sublime/User" "$sublime_dir"
ln -s "$ZSH/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/sublime

# Grab the Soda theme
cd "$sublime_dir"
# git clone https://github.com/buymeasoda/soda-theme/ "Theme - Soda"
# git clone https://github.com/tomasr/molokai "Theme - Molokai"
